### ISSUE TITLE
Add a quick test program for LDAP

### ISSUE THREAD

**Issue by olivierlambert** [vatesfr/xo-server-auth-ldap#6]
Because LDAP configurations are very heterogeneous, we need to integrate a small test program in this plugin to allow users to validate their config faster (by trials & errors) without using `xo-web`.

We could also have the debug level at max by default (because it's a test tool by nature)

See https://github.com/julien-f/ldap-test

**Comment by julien-f** [comment]
Implemented a long time ago.
