### ISSUE TITLE
Save configuration : Fail for unknown reason

### ISSUE THREAD

**Issue by sgrunt91** [vatesfr/xo-server-auth-ldap#7]
Hi,

First, I would like to thanks all of you for this beautiful project, and for the open-source orientation !

I've installed an xo environnment  which works well for all.
Now, I would like to connect it to a LDAP server.

I've installed `xo-server-auth-ldap` with `npm`.

The connection with `node_modules/xo-server-auth-ldap/dist/test-cli.js` works well, but when I'm trying to set my configuration in the Web interface I got an orange popup that say:
`Sets the configuration a plugin`
`The action failed for unknown reason`

I would like to know where I can find logs ? 
I'm running `xo-server` with `forever` but I also tried to run it in the prompt with `npm start` but I don't find any error message.

Have you any idea ? 

I know that I'm not using a Pro version, so if you don't have time for support my case it's OK, but it doesn't hurt to ask :)

Best Regards !

**Comment by olivierlambert** [comment]
Thanks for reporting thins @sgrunt91 . We'll take a look as soon as we can :) (we are a small team, so it's hard to be everywhere, but again, we'll check this!)

**Comment by julien-f** [comment]
@sgrunt91 I'm closing this issue, feel free to comment if you still have problems with latest versions.
